Lab1: main.o read.o sort.o print.o
	g++ -o lab1 main.o read.o sort.o print.o

main.o: main.cc Lab1.h
	g++ -c main.cc

read.o: read.cc Lab1.h
	g++ -c read.cc

sort.o: sort.cc Lab1.h
	g++ -c sort.cc

print.o: print.cc Lab1.h
	g++ -c print.cc
